export const FETCH_DATA_ACTION = 'FETCH_DATA_ACTION'
export const SANITIZED_DATA_ACTION = 'SANITIZED_DATA_ACTION'
export const CLEAR_ACTION = 'CLEAR_ACTION'
export const UPDATE_TEXT_ACTION = 'UPDATE_TEXT_ACTION'